# Defines a default set of lint rules enforced for
# projects at Google. For details and rationale,
# see https://github.com/dart-lang/pedantic#enabled-lints.
include: package:pedantic/analysis_options.yaml

# For lint rules and documentation, see http://dart-lang.github.io/linter/lints.
# Uncomment to specify additional rules.
linter:
  rules:
    - camel_case_types
    - parameter_assignments

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  # TODO: This shouldn't be excluded but the types on parsers are hard for me
  exclude:
    - "**/*_parser.dart"