name: arb_translator
description: A command-line utility which helps to translate arb files with the use of google translations.
version: 1.0.4
homepage: https://github.com/justkawal/arb_translator.git

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  path: ^1.8.0
  args: ^2.1.0
  http: ^0.13.2
  console: ^4.1.0
  test: ^1.17.3
  petitparser: ^4.0.2
  html_unescape: ^2.0.0

dev_dependencies:
  pedantic: ^1.11.0
  