name: arb_translator
description: A command-line utility which helps to translate arb files.
version: 1.0.3
homepage: https://github.com/justkawal/arb_translator.git

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  path: ^1.8.0
  args: ^2.0.0
  http: ^0.13.0
  dart_console: ^1.0.0
  test: ^1.16.5
  petitparser: ^4.0.2
  html_unescape: ^2.0.0-nullsafety.0

dev_dependencies:
  pedantic: ^1.11.0
  