name: arb_translator
description: A command-line utility which helps to translate arb files with the use of google translations.
version: 3.0.0
homepage: https://github.com/justkawal/arb_translator.git

environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:
  args: ^2.5.0
  collection: ^1.19.0
  console: ^4.1.0
  html_unescape: ^2.0.0
  http: ^1.2.2
  path: ^1.9.0
  petitparser: ^6.0.2
  yaml: ^3.1.2
dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.8
